version: '3'

services:
  selenoid:
    image: "aerokube/selenoid"
    network_mode: bridge
    depends_on:
      - chrome123
      - chrome124
    ports:
      - "4444:4444"
    volumes:
      - "/Users/sergeyfrolkin/.jenkins/workspace/final_project/:/etc/selenoid/" # assumed current dir contains browsers.json
      - "/var/run/docker.sock:/var/run/docker.sock"

  selenoid-ui:
    image: "aerokube/selenoid-ui"
    network_mode: bridge
    depends_on:
      - selenoid
    links:
      - selenoid
    ports:
      - "8090:8080"
    command: [ "--selenoid-uri", "http://${EX_IP}:4444" ]

  chrome124:
    image: selenoid/chrome:124.0

  chrome123:
    image: selenoid/chrome:123.0

  tests:
    image: tests_container:v1
    build:
      dockerfile: tests/Dockerfile
    depends_on:
      - selenoid-ui
    command: pytest /tests -n ${N} --panel ${PANEL} --stand ${STAND} --ex_ip ${EX_IP} --browser ${BROWSER} --bv ${BV} --component_id ${COMPONENT} --employee ${EMPLOYEE} --login_type ${LOGINTYPE} --vnc
    container_name: tests_container
    networks:
      - test_net
    volumes:
      - "/Users/sergeyfrolkin/.jenkins/workspace/final_project/allure-results/:/allure-results/"
      - "/Users/sergeyfrolkin/.jenkins/workspace/final_project/tests/logs/:/tests/logs/"

networks:
  test_net:

volumes:
  mariadb_data:
    driver: local
  opencart_data:
    driver: local
  opencart_storage_data:
    driver: local
